name: ci-test

on: { push: { branches: [ "**" ] } }

jobs:
  test-tag: # job id
    timeout-minutes: 8
    strategy:
      fail-fast: false # allow all test to run to the end
      matrix:
        os: [ "ubuntu-latest" ]
        node-version: [ "14.x", "18.x" ]
    runs-on: "${{ matrix.os }}"
    steps:
      - { uses: "actions/checkout@v2" } # https://github.com/actions/checkout
      - { uses: "actions/setup-node@v2", with: { node-version: "${{ matrix.node-version }}" } } # https://github.com/actions/setup-node
      - run: npx @dr-js/dev@0.4 -eI .github/ci-patch.js
      - run: npm ci
      - run: npm test
