name: ci-test

on:
  push: { branches: [ "**" ] }

jobs:
  build:
    strategy:
      fail-fast: false # allow all test to run to the end
      matrix:
        os: [ ubuntu-latest ]
        node-version: [ 14.x, 15.x ]

    runs-on: "${{ matrix.os }}"

    steps:
      - uses: actions/checkout@v2 # https://github.com/actions/checkout
      - uses: actions/setup-node@v2 # https://github.com/actions/setup-node
        with: { node-version: "${{ matrix.node-version }}" }

      - name: Log CI info
        run: |
          echo "system: $(node -p "os.platform() + ' - ' + os.release() + ' [' + os.arch() + ']'")"
          echo "node: $(node -v)"
          echo "npm: $(npm -v)"

      - run: npm ci
      - run: npm test
